# compose file format version based on Docker engine release 19.03.0+
version: "3.8"

services:
  # define our individual services

  flask:
    # build the flask service using the Dockerfile in the flask directory
    build: ./flask
    # instruct Docker to always restart the service
    restart: always
    # use environment to set any environment variables
    environment:
      - APP_NAME=MyFlaskApp
    # exposes internal ports to other containers/services on the same network
    # redis will be serving our Flask application on port 6379
    # expose:
    #   - 6379
    ports:
     - "5000:5000"
    # mount the container log directory to the local log directory
    # consider changing this to /var/log/uwsgi:/var/log/uwsgi in production
    # just make sure the directory exists before running docker-compose up --build
    # volumes:
    #   - ./log/uwsgi:/var/log/uwsgi

  redis:
    # build the redis service using the Dockerfile in the redis directory
    build: ./redis
    # NOTE: it causes problem
    # instruct Docker to always restart the service
    # restart: always
    # any ports listed using `ports` will be exposed to the outside world
    ports:
      - "6379:6379"
    # mount the container log directory to the local log directory
    # consider changing this to /var/log/redis:/var/log/redis in production
    # just make sure the directory exists before running docker-compose up --build
    # volumes:
    #   - ./log/redis:/var/log/redis
